[package]
name = "isolation_forest"
version = "1.1.0"
authors = ["Michael J Simms <msimms01@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1"
