[package]
name = "isolation_forest"
version = "0.9.0"
authors = ["Michael J Simms <msimms01@gmail.com>"]

[dependencies]
rand = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
